#!/usr/bin/env sh

# Check if wleave is already running
if pgrep -x "wleave" > /dev/null
then
    pkill -x "wleave"
    exit 0
fi

wlColms=6
wLayout="$HOME/.config/wleave/layout"
if [ ! -f "$HOME/.config/wleave/gen_style.css" ]; then
    # set file variables
    ScrDir=`dirname $(realpath $0)`
    source $ScrDir/globalcontrol
    wlTmplt="$HOME/.config/wleave/style.css"

    if [ ! -f $wLayout ] || [ ! -f $wlTmplt ] ; then
        echo "ERROR: Config $1 not found..."
        exit 1;
    fi

    # detect monitor res
    x_mon=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .width')
    y_mon=$(hyprctl -j monitors | jq '.[] | select(.focused==true) | .height')
    hypr_scale=$(hyprctl -j monitors | jq '.[] | select (.focused == true) | .scale' | sed 's/\.//')


    # scale config layout and style
    export mgn=$(( y_mon * 38 / hypr_scale ))
    export hvr=$(( y_mon * 33 / hypr_scale ))

    # scale font size
    export fntSize=$(( y_mon * 2 / 100 ))

    # detect gtk system theme
    export BtnCol="white"
    export WindBg="rgba(0,0,0,0.5)"

    # eval hypr border radius
    export active_rad=$(( hypr_border * 5 ))
    export button_rad=$(( hypr_border * 8 ))

    # eval config files
    (envsubst < $wlTmplt) > $HOME/.config/wleave/gen_style.css
fi

# launch wleave
wleave -b $wlColms -c 0 -r 0 -m 0 --layout $wLayout --css $HOME/.config/wleave/gen_style.css --protocol layer-shell
