#!/usr/bin/env sh

# set variables

ScrDir=`dirname $(realpath $0)`
source $ScrDir/globalcontrol
dstDir="$HOME/.config/dunst"

# regen conf

cat $dstDir/dunst.conf $dstDir/Wall-Dcol.conf > $dstDir/dunstrc
killall dunst
dunst &

