theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
cursorline = true
color-modes = true
true-color = true
shell = ["nu", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false
git-ignore = true

[editor.lsp]
display-messages = true
